### ISSUE TITLE
Query Timeout having no effect

### ISSUE THREAD

**Issue by vishjosh** [bippio/go-impala#18]
`
package main

import (
	"context"
	"database/sql"
	"log"

	imp "github.com/bippio/go-impala"
)

func main() {

	opts := imp.DefaultOptions

	opts.Host = "some_host"
	opts.Port = "21050"

	// enable LDAP authentication:
	opts.UseLDAP = true
	opts.Username = "xx"
	opts.Password = "yy"

	// enable TLS
	opts.UseTLS = true
	opts.CACertPath = "/opt/bipp/certs/zz.pem"

	opts.QueryTimeout = 1

	connector := imp.NewConnector(&opts)
	db := sql.OpenDB(connector)
	defer db.Close()

	ctx := context.Background()

	rows, err := db.QueryContext(ctx, "Loooong running query (use a self-join to simulate one)")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()

	type Record struct {
		rec1   string
		//rec2  string
		//rec3 int
	}

	var record Record

	results := make([]Record, 0)
	for rows.Next() {
		if err := rows.Scan(&record.rec1); err != nil {
			log.Fatal(err)
		}
		results = append(results, record)
	}
	if err := rows.Err(); err != nil {
		log.Fatal(err)
	}
	log.Println("Results", results)
}

`

Tried the above code on a long running query, the query timeout never kicked in. Are we doing something wrong or is there some other issue ?

**Comment by intamyuto** [comment]
I figured that this option (QUERY_TIMEOUT_S) works for IDLE queries. Thats why it isn't working here. Found another option in documentation (EXEC_TIME_LIMIT_S) but failed to set it with hiveserver2 api.

Main issue is that I can't understand why timeout with context.Context is not working. It's the most correct way to cancel rpc request. @vishjosh, can you please check if it work in your particular case?

Just replace 
```
ctx := context.Background()
```
with:
```
ctx, cancel := context.WithTimeout(context.Background(), time.Second)
defer cancel()
```
You should get something like: 
```
2019/06/05 16:05:46 context deadline exceeded
exit status 1
```

**Comment by sauravhaloi** [comment]
yes, implemented the timeout thing using context with timeout in lieu of QUERY_TIMEOUT_S and it works.
