### ISSUE TITLE
Reestablish connection after EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by hbizunehe** [bippio/go-impala#22]
Hi!

First, thanks for the great work :)

I came across the issue that when a "broken pipe" error thrown by the net package, the driver keeps using the connection instead of either abandon it or re-establish a new connection by closing the existing one and opening a new one. The problem will persist forever unless connection max lifetime is set in that case the bad connection will be closed at time T when it reaches its lifetime.

Here is how you can re-produce the scenario manually.

1) Run example program
2) Take the port number from local address. For example 1234 based on the following example
```
sudo netstat -anp | grep 21050
tcp        0      0 x.x.x.x:1234     y.y.y.y:21050    ESTABLISHED 100000/impala-example
```
3) Kill the connection to create a broken pipe senario as follows
```
sudo tcpkill -i eth0 -9 port 1234
```
4) Make your example program execute a query and you will get "broken pipe" errors

I tried to see if closing and opening a connection in "broken pipe" state fixes the problem during [OpenSession](https://github.com/bippio/go-impala/blob/master/connection.go#L90) and indeed it will fix the issue but I'm not sure if that is the right place to put the fix.

**Comment by intamyuto** [comment]
Hello! 

Yes, handling broken connection during OpenSession is a good place. Thanks for the suggestion.
I think we can safely abandon connection on any error during OpenSession. Please check the PR and confirm it is helping you case.

Once again thanks for finding time to file an issue. We appreciate it.

**Comment by hbizunehe** [comment]
Hi !

Thanks for the fix. Yea `driver.ErrBadConn` is a good solution as it makes the sql package to retry a new connection and execute the query. I tried it also and works as expected :)
