### ISSUE TITLE
Error in cli_service.go: argument 1 has incompatible type (missing method 'Deadline')

### ISSUE THREAD

**Issue by advancedwebdeveloper** [bippio/go-impala#24]
Hi.

Here is what I got:

$ go build -i -v -x
WORK=/tmp/go-build219060932
github.com/bippio/go-impala/sasl
mkdir -p $WORK/b035/
cd $WORK
/home/oceanfish81/gollvm_dist/bin/llvm-goc -fgo-importcfg=/dev/null -c -x c - -o /dev/null || true
github.com/bippio/go-impala/services/cli_service
mkdir -p $WORK/b035/_importcfgroot_/github.com/apache/thrift/lib/go
mkdir -p $WORK/b033/
ln -s /home/oceanfish81/go/pkg/gccgo_linux_amd64/github.com/apache/thrift/lib/go/libthrift.a $WORK/b035/_importcfgroot_/github.com/apache/thrift/lib/go/libthrift.a
cd /home/oceanfish81/go/src/github.com/bippio/go-impala/sasl
/home/oceanfish81/gollvm_dist/bin/llvm-goc -c -O2 -g -m64 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=github.com/bippio/go-impala/sasl -o $WORK/b035/_go_.o -I $WORK/b035/_importcfgroot_ ./client.go ./plain.go ./sasl.go ./transport.go
mkdir -p $WORK/b033/_importcfgroot_/github.com/apache/thrift/lib/go
ln -s /home/oceanfish81/go/pkg/gccgo_linux_amd64/github.com/apache/thrift/lib/go/libthrift.a $WORK/b033/_importcfgroot_/github.com/apache/thrift/lib/go/libthrift.a
cd /home/oceanfish81/go/src/github.com/bippio/go-impala/services/cli_service
/home/oceanfish81/gollvm_dist/bin/llvm-goc -c -O2 -g -m64 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=github.com/bippio/go-impala/services/cli_service -o $WORK/b033/_go_.o -I $WORK/b033/_importcfgroot_ ./GoUnusedProtection__.go ./cli_service-consts.go ./cli_service.go
echo '	.section .go.buildid,"e"' >> $WORK/b035/_buildid.s
echo '	.byte 0x65,0x5a,0x48,0x72,0x6e,0x6f,0x37,0x55' >> $WORK/b035/_buildid.s
echo '	.byte 0x38,0x6d,0x50,0x79,0x2d,0x5a,0x55,0x67' >> $WORK/b035/_buildid.s
echo '	.byte 0x62,0x74,0x65,0x35,0x2f,0x65,0x5a,0x48' >> $WORK/b035/_buildid.s
echo '	.byte 0x72,0x6e,0x6f,0x37,0x55,0x38,0x6d,0x50' >> $WORK/b035/_buildid.s
echo '	.byte 0x79,0x2d,0x5a,0x55,0x67,0x62,0x74,0x65' >> $WORK/b035/_buildid.s
echo '	.byte 0x35' >> $WORK/b035/_buildid.s
echo '	.section .note.GNU-stack,"",@progbits' >> $WORK/b035/_buildid.s
echo '	.section .note.GNU-split-stack,"",@progbits' >> $WORK/b035/_buildid.s
echo '' >> $WORK/b035/_buildid.s
cd /home/oceanfish81/go/src/github.com/bippio/go-impala/sasl
/home/oceanfish81/gollvm_dist/bin/llvm-goc -xassembler-with-cpp -I $WORK/b035/ -c -o $WORK/b035/_buildid.o -D GOOS_linux -D GOARCH_amd64 -D GOPKGPATH=github.x2ecom..z2fbippio..z2fgo..z2dimpala..z2fsasl -m64 $WORK/b035/_buildid.s
ar rcD $WORK/b035/_pkg_.a $WORK/b035/_go_.o $WORK/b035/_buildid.o
/home/oceanfish81/gollvm_dist/tools/buildid -w $WORK/b035/_pkg_.a # internal
cp $WORK/b035/_pkg_.a /home/oceanfish81/.cache/go-build/6c/6c13564ac1673b97012d5556cd1ad55e6d447aed60c32985670182c34e830221-d # internal
mkdir -p /home/oceanfish81/go/pkg/gccgo_linux_amd64/github.com/bippio/go-impala/
mv $WORK/b035/_pkg_.a /home/oceanfish81/go/pkg/gccgo_linux_amd64/github.com/bippio/go-impala/libsasl.a
rm -r $WORK/b035/
# github.com/bippio/go-impala/services/cli_service
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:721:21: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:727:42: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:739:30: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:739:24: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:749:30: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:749:24: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:754:28: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:754:22: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:758:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:762:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:769:21: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:778:21: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:790:55: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:790:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:796:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:798:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:805:45: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:805:56: error: argument 2 has incompatible type (cannot use type int as type string)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:805:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:807:30: error: argument 1 has incompatible type (type has no methods)

**Comment by advancedwebdeveloper** [comment]
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:807:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:809:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:817:48: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:817:59: error: argument 2 has incompatible type (cannot use type int as type string)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:817:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:819:33: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:819:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:821:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:849:21: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:856:42: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:869:30: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:869:24: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:874:28: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:874:22: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:878:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:882:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:892:27: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:900:23: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:911:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:918:51: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:918:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:923:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:925:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:931:45: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:931:56: error: argument 2 has incompatible type (cannot use type int as type string)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:931:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:933:40: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:933:63: error: argument 3 has incompatible type (cannot use type int as type thrift.TType)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:933:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:937:33: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:937:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:943:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:946:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:986:21: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:993:42: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1006:30: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1006:24: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1016:30: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1016:24: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1021:28: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1021:22: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1025:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1029:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1039:21: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1057:55: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1057:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1063:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1065:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1071:39: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1071:50: error: argument 2 has incompatible type (cannot use type int as type string)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1071:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1073:28: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1073:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1075:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1082:51: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1082:62: error: argument 2 has incompatible type (cannot use type int as type string)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1082:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1087:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1115:21: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1122:42: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1135:30: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1135:24: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1140:28: error: argument 1 has incompatible type (missing method 'Deadline')
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1140:22: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1144:20: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1148:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1158:21: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1168:51: error: argument 1 has incompatible type (type has no methods)

**Comment by advancedwebdeveloper** [comment]
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1168:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1173:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1175:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1181:48: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1181:59: error: argument 2 has incompatible type (cannot use type int as type string)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1181:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1183:28: error: argument 1 has incompatible type (type has no methods)
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1183:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1185:18: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1218:21: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1226:42: error: not enough arguments
../../go/src/github.com/bippio/go-impala/services/cli_service/cli_service.go:1239:30: error: argument 1 has incompatible type (missing method 'Deadline')

**Comment by advancedwebdeveloper** [comment]
I am using 

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

under Ubuntu 20 x86_64

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build333483145=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
>

**Comment by shaloi** [comment]
Can you please post the version of Thrift in your build environment. You may find this information in the file `$GOPATH/src/github.com/apache/thrift/README.md`

The `go-impala` library has been tested till Thrift version 0.12.0

**Comment by advancedwebdeveloper** [comment]
> Can you please post the version of Thrift in your build environment. You may find this information in the file `$GOPATH/src/github.com/apache/thrift/README.md`
> 
> The `go-impala` library has been tested till Thrift version 0.12.0

@shaloi ,
I am seeing this:

Status
======

> | [`master`](https://github.com/apache/thrift/tree/master) | [![Build Status](https://travis-ci.org/apache/thrift.svg?branch=master)](https://travis-ci.org/apache/thrift/branches) | [![Build status](https://ci.appveyor.com/api/projects/status/github/apache/thrift?branch=master&svg=true)](https://ci.appveyor.com/project/ApacheSoftwareFoundation/thrift/history) | [![Coverity Scan Build Status](https://scan.coverity.com/projects/1345/badge.svg)](https://scan.coverity.com/projects/thrift) | | [![Website](https://img.shields.io/badge/official-website-brightgreen.svg)](https://thrift.apache.org/) |
> | [`**0.13.0**`](https://github.com/apache/thrift/tree/0.13.0) | [![Build Status](https://travis-ci.org/apache/thrift.svg?branch=0.13.0)](https://travis-ci.org/apache/thrift/branches) | | | | |
> | [`**0.12.0**`](https://github.com/apache/thrift/tree/0.12.0) | [![Build Status](https://travis-ci.org/apache/thrift.svg?branch=0.12.0)](https://travis-ci.org/apache/thrift/branches) | | | | |
>

**Comment by shaloi** [comment]
Okay. It seems like you are on Thrift **0.13.0**. Lets try with Thrift version **0.12.0**. Depending on the package management tool your project uses, the way of getting a specific version of a package will be different. So. lets try it the naive way:

```
$ cd $GOPATH/src/github.com/apache        # go to the Apache Thrift package directory in the system GOPATH
$ mv -f thrift thrift.0.13.0        # take a backup of the existing thrift directory
$ wget https://github.com/apache/thrift/archive/v0.12.0.tar.gz       # download Thrift version 0.12.0
$ tar -zxf v0.12.0.tar.gz && mv -f thrift-0.12.0 thrift        # extract the downloaded Thrift version 0.12.0 tarball
```
Now try building your project and let us know the outcome.

**Comment by advancedwebdeveloper** [comment]
I just did as you proposed.
It looks like the files where compiled:

> $ go build -i -v -x
> WORK=/tmp/go-build047381096
> github.com/apache/thrift/lib/go/thrift
> mkdir -p $WORK/b007/
> cd $WORK
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -fgo-importcfg=/dev/null -c -x c - -o /dev/null || true
> cd /home/oceanfish81/go/src/github.com/apache/thrift/lib/go/thrift
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -c -O2 -g -m64 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=github.com/apache/thrift/lib/go/thrift -o $WORK/b007/_go_.o -I $WORK/b007/_importcfgroot_ ./application_exception.go ./binary_protocol.go ./buffered_transport.go ./client.go ./compact_protocol.go ./context.go ./debug_protocol.go ./deserializer.go ./exception.go ./field.go ./framed_transport.go ./http_client.go ./http_transport.go ./iostream_transport.go ./json_protocol.go ./memory_buffer.go ./messagetype.go ./multiplexed_protocol.go ./numeric.go ./pointerize.go ./processor_factory.go ./protocol.go ./protocol_exception.go ./protocol_factory.go ./rich_transport.go ./serializer.go ./server.go ./server_socket.go ./server_transport.go ./simple_json_protocol.go ./simple_server.go ./socket.go ./ssl_server_socket.go ./ssl_socket.go ./transport.go ./transport_exception.go ./transport_factory.go ./type.go ./zlib_transport.go
> echo '	.section .go.buildid,"e"' >> $WORK/b007/_buildid.s
> echo '	.byte 0x33,0x39,0x4d,0x30,0x6c,0x2d,0x65,0x56' >> $WORK/b007/_buildid.s
> echo '	.byte 0x31,0x65,0x68,0x70,0x56,0x76,0x66,0x38' >> $WORK/b007/_buildid.s
> echo '	.byte 0x49,0x57,0x5f,0x49,0x2f,0x33,0x39,0x4d' >> $WORK/b007/_buildid.s
> echo '	.byte 0x30,0x6c,0x2d,0x65,0x56,0x31,0x65,0x68' >> $WORK/b007/_buildid.s
> echo '	.byte 0x70,0x56,0x76,0x66,0x38,0x49,0x57,0x5f' >> $WORK/b007/_buildid.s
> echo '	.byte 0x49' >> $WORK/b007/_buildid.s
> echo '	.section .note.GNU-stack,"",@progbits' >> $WORK/b007/_buildid.s
> echo '	.section .note.GNU-split-stack,"",@progbits' >> $WORK/b007/_buildid.s
> echo '' >> $WORK/b007/_buildid.s
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -xassembler-with-cpp -I $WORK/b007/ -c -o $WORK/b007/_buildid.o -D GOOS_linux -D GOARCH_amd64 -D GOPKGPATH=github.x2ecom..z2fapache..z2fthrift..z2flib..z2fgo..z2fthrift -m64 $WORK/b007/_buildid.s
> ar rcD $WORK/b007/_pkg_.a $WORK/b007/_go_.o $WORK/b007/_buildid.o
> /home/oceanfish81/gollvm_dist/tools/buildid -w $WORK/b007/_pkg_.a # internal
> cp $WORK/b007/_pkg_.a /home/oceanfish81/.cache/go-build/7e/7e8375f896cdf023bae13fb205df78939a214d65a673ec967729cecfbac4a342-d # internal
> mkdir -p /home/oceanfish81/go/pkg/gccgo_linux_amd64/github.com/apache/thrift/lib/go/
> mv $WORK/b007/_pkg_.a /home/oceanfish81/go/pkg/gccgo_linux_amd64/github.com/apache/thrift/lib/go/libthrift.a
> rm -r $WORK/b007/
> _/home/oceanfish81/go_projects/go-impala/sasl
> mkdir -p $WORK/b001/
> mkdir -p $WORK/b001/_importcfgroot_/github.com/apache/thrift/lib/go
> ln -s /home/oceanfish81/go/pkg/gccgo_linux_amd64/github.com/apache/thrift/lib/go/libthrift.a $WORK/b001/_importcfgroot_/github.com/apache/thrift/lib/go/libthrift.a
> cd /home/oceanfish81/go_projects/go-impala/sasl
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -c -O2 -g -m64 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=_/home/oceanfish81/go_projects/go-impala/sasl -fgo-relative-import-path=_/home/oceanfish81/go_projects/go-impala/sasl -o $WORK/b001/_go_.o -I $WORK/b001/_importcfgroot_ ./client.go ./plain.go ./sasl.go ./transport.go
> echo '	.section .go.buildid,"e"' >> $WORK/b001/_buildid.s
> echo '	.byte 0x31,0x71,0x53,0x74,0x48,0x57,0x47,0x4a' >> $WORK/b001/_buildid.s
> echo '	.byte 0x44,0x6e,0x34,0x56,0x6e,0x43,0x53,0x43' >> $WORK/b001/_buildid.s
> echo '	.byte 0x55,0x43,0x4c,0x49,0x2f,0x31,0x71,0x53' >> $WORK/b001/_buildid.s
> echo '	.byte 0x74,0x48,0x57,0x47,0x4a,0x44,0x6e,0x34' >> $WORK/b001/_buildid.s
> echo '	.byte 0x56,0x6e,0x43,0x53,0x43,0x55,0x43,0x4c' >> $WORK/b001/_buildid.s
> echo '	.byte 0x49' >> $WORK/b001/_buildid.s
> echo '	.section .note.GNU-stack,"",@progbits' >> $WORK/b001/_buildid.s
> echo '	.section .note.GNU-split-stack,"",@progbits' >> $WORK/b001/_buildid.s
> echo '' >> $WORK/b001/_buildid.s
> /home/oceanfish81/gollvm_dist/bin/llvm-goc -xassembler-with-cpp -I $WORK/b001/ -c -o $WORK/b001/_buildid.o -D GOOS_linux -D GOARCH_amd64 -D GOPKGPATH=_..z2fhome..z2foceanfish81..z2fgo_projects..z2fgo..z2dimpala..z2fsasl -m64 $WORK/b001/_buildid.s
> ar rcD $WORK/b001/_pkg_.a $WORK/b001/_go_.o $WORK/b001/_buildid.o
> /home/oceanfish81/gollvm_dist/tools/buildid -w $WORK/b001/_pkg_.a # internal
> cp $WORK/b001/_pkg_.a /home/oceanfish81/.cache/go-build/5f/5fbbd08d478407e9ca8b6863b52cc3bfa684ebcbb22632a3cf1d7ee1398093ec-d # internal
>

**Comment by shaloi** [comment]
Great. I will update the documentation about the supported Thrift versions. Shall I close the issue as resolved?

**Comment by advancedwebdeveloper** [comment]
Please open an issue, for migrating to Thrift 0.13 - and provide a patch, so v0.12 would be obtained automatically (as for now).

As for this issue - this surely might be closed.
I think tests for go-impala are working - but I will search for end-user use cases, in the future.
Thanks

**Comment by shaloi** [comment]
Currently this project uses `dep` as the package management tool where the dependency on Apache Thrift 0.12 is specified. We have plans to move to using go modules soon.
