### ISSUE TITLE
execute query while no response

### ISSUE THREAD

**Issue by qizhelongdeyang** [bippio/go-impala#3]
I tried this demo on CDH cluster with no authorization, code like this
func main() {
	host := "cloudera.demo"
	port := 21050

	opts := impalathing.DefaultOptions

	con, err := impalathing.Connect(host, port, &opts)
	if err != nil {
		log.Fatal(err)
	}

	query, err := con.Query(context.Background(), "select 1")

	startTime := time.Now()
	results := query.FetchAll(context.Background())
	log.Printf("Fetch %d rows(s) in %.2fs", len(results), time.Duration(time.Since(startTime)).Seconds())
}

while the query is hunging in the step "con.Query"，no response

**Comment by paribhasha** [comment]
Can you try running your code at port 21000?

**Comment by qizhelongdeyang** [comment]
thank you for your response, the port is exactly 21000 
(ps:port 21050 is for jdbc)

**Comment by paribhasha** [comment]
Cool. Please let us know if you encounter any issues.
