### ISSUE TITLE
Errors from cli_service.go

### ISSUE THREAD

**Issue by mark-hughes-nuspire** [bippio/go-impala#31]
Having trouble getting and building (cli_service.go).  This maybe similar to Thrift version Issue #24.  I tried to resolve with solution in #24 but was unsuccessful.  I even tried 'go clean -cache' to be sure but no luck.

mark@MarkHughes:~/go/src/DBL_168/nusiem-device-create-hive-tables$ go build -v -x
WORK=/tmp/go-build437803886
github.com/bippio/go-impala/services/cli_service
mkdir -p $WORK/b122/
cat >$WORK/b122/importcfg << 'EOF' # internal
# import config
packagefile bytes=/usr/local/go/pkg/linux_amd64/bytes.a
packagefile context=/usr/local/go/pkg/linux_amd64/context.a
packagefile database/sql/driver=/usr/local/go/pkg/linux_amd64/database/sql/driver.a
packagefile errors=/usr/local/go/pkg/linux_amd64/errors.a
packagefile fmt=/usr/local/go/pkg/linux_amd64/fmt.a
packagefile github.com/apache/thrift/lib/go/thrift=/home/mark/.cache/go-build/66/66bfbb0508076af1b7ccdac2ef12b2a7adffd3de8fcb1355c3ca10528079b032-d
packagefile reflect=/usr/local/go/pkg/linux_amd64/reflect.a
EOF
cd /home/mark/go/src/DBL_168/nusiem-device-create-hive-tables
/usr/local/go/pkg/tool/linux_amd64/compile -o $WORK/b122/_pkg_.a -trimpath "$WORK/b122=>" -p github.com/bippio/go-impala/services/cli_service -complete -buildid akEEO3jNMNkzO7vPVkKV/akEEO3jNMNkzO7vPVkKV -goversion go1.16 -D "" -importcfg $WORK/b122/importcfg -pack -c=4 /home/mark/go/pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/GoUnusedProtection__.go /home/mark/go/pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service-consts.go /home/mark/go/pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go
# github.com/bippio/go-impala/services/cli_service
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:721:37: not enough arguments in call to iprot.ReadStructBegin
	have ()
	want (context.Context)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:727:57: not enough arguments in call to iprot.ReadFieldBegin
	have ()
	want (context.Context)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:739:29: not enough arguments in call to iprot.Skip
	have (thrift.TType)
	want (context.Context, thrift.TType)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:758:33: not enough arguments in call to iprot.ReadFieldEnd
	have ()
	want (context.Context)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:762:32: not enough arguments in call to iprot.ReadStructEnd
	have ()
	want (context.Context)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:769:29: not enough arguments in call to iprot.ReadI32
	have ()
	want (context.Context)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:778:32: not enough arguments in call to iprot.ReadString
	have ()
	want (context.Context)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:790:35: not enough arguments in call to oprot.WriteStructBegin
	have (string)
	want (context.Context, string)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:796:33: not enough arguments in call to oprot.WriteFieldStop
	have ()
	want (context.Context)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:798:33: not enough arguments in call to oprot.WriteStructEnd
	have ()
	want (context.Context)
../../../pkg/mod/github.com/bippio/go-impala@v2.1.0+incompatible/services/cli_service/cli_service.go:798:33: too many errors
mark@MarkHughes:~/go/src/DBL_168/nusiem-device-create-hive-tables$

**Comment by mark-hughes-nuspire** [comment]
Found a workaround...

**Comment by nineinchnick** [comment]
@mark-hughes-nuspire can you share what's the workaround?

**Comment by mark-hughes-nuspire** [comment]
Yes, we used ODBC.

**Comment by clpluie** [comment]
@mark-hughes-nuspire  why example is still database/sql

**Comment by mangup** [comment]
@mark-hughes-nuspire you mean - you had rid off from bippio/go-imala and switched to other odbc package?
