### ISSUE TITLE
How to use( use databases)

### ISSUE THREAD

**Issue by Flyingmn** [bippio/go-impala#40]
My function needs to select the database to execute sql, otherwise an error will be reported:

`error:QueryContest:AnalysisException: Could not resolve table reference: 'user_tag_view_user_group_hyyhhd4dbbzyws_production'`

However, it does not take effect after use is executed

```
if _, err := DB.ExecContext(ctx, "use rawdata"); err != nil {
         return res, fmt.Errorf("use rawdata:%v", err)
}
```

**Comment by murfffi** [comment]
This is an old issue but in case anybody is still wondering about this ...

"use" applies only to a single connection so make sure you are using the same one. Multiple Exec or Query calls to the DB object go to different DB connections. Instead use a Conn object like this:

```go
ctx := // some context
conn, err := DB.Conn(ctx)
// check err
defer conn.Close()
_, err = conn.ExecContext(ctx, "use rawdata")
// check err
res, err := conn.QueryContext(ctx, "select * sometable")
// sometable should be correctly resolved as  rawdata.sometable
```
