### ISSUE TITLE
Issues when query returns lots of records/rows

### ISSUE THREAD

**Issue by vishjosh** [bippio/go-impala#5]
[impala.go.txt](https://github.com/bippio/go-impala/files/2849575/impala.go.txt)

We are running the attached client program to iterate all the DBs and then iterate the tables for each DB.

We realized there are 2 issues :

- Issue 1:  Some DBs had more than 1K tables . 
   - Interestingly the Fetch call below in rowset's Next() function would succeed (the response's data would be arbitrarily truncated which goes unnoticed) , but the RowSet's Next() call would finally fail with following error (which also goes unnoticed by the client - all that the client knows is that there are no results to iterate through)
 **GetResultsMetadata failed: get_results_metadata: wrong method name**
   - https://github.com/bippio/go-impala/blob/e316686dfb0394346755335508b8320bdf0b5964/rowset.go#L140
   - The solution seems to make sure that the fetch call requests lower number of rows , however it is not clear what the right number should be . 100 seems to work . 1000 seems to be too high.

- Issue 2 , Interestingly after the Next() call errors out, it just returns false and the client code moves on to the next query .  However all subsequent queries on that connection fail with the following error . This is extremely problematic, ideally we should be able to reset the state and start a new query even if earlier queries error out.
   -  **error in querying database X: query: wrong method name**

@timarmstrong - I would need some suggestion from you on both the issues .

Both issues seem to be stemming due to the driver's incorrect understanding of how to use the thrift interface/services. 
Any help will be appreciated to point us to a more robust way of doing this without changing the current dependency on beeswax.

@intamyuto  FYI

**Comment by timarmstrong** [comment]
I tried to reproduce this on my dev environment (master Impala, no security) and it seems to work fine for a database with many tables. https://github.com/timarmstrong/go-impala-repro

If you can reproduce this on a non-production environment with verbose logging set to 3, I'd be interested in seeing the impalad INFO logs, since those will log most of the RPCs sent from the client to the server and the responses.

**Comment by timarmstrong** [comment]
E.g. here's the log output I see locally
`I0211 08:57:47.067507  3533 impala-beeswax-server.cc:54] query(): query=SHOW TABLES IN go_impala_repro
I0211 08:57:47.067520  3533 impala-beeswax-server.cc:432] query: Query {
  01: query (string) = "SHOW TABLES IN go_impala_repro",
  03: configuration (list) = list<string>[0] {
  },
  04: hadoop_user (string) = "",
}
I0211 08:57:47.067538  3533 impala-server.cc:895] Parsed pool options:  override_options_mask=11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111 set_pool_mask=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 overlay_mask=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
I0211 08:57:47.067572  3533 impala-beeswax-server.cc:465] TClientRequest.queryOptions: TQueryOptions {
  01: abort_on_error (bool) = false,
  02: max_errors (i32) = 100,
  03: disable_codegen (bool) = false,
  04: batch_size (i32) = 0,
  05: num_nodes (i32) = 0,
  06: max_scan_range_length (i64) = 0,
  07: num_scanner_threads (i32) = 0,
  11: debug_action (string) = "",
  12: mem_limit (i64) = 0,
  15: hbase_caching (i32) = 0,
  16: hbase_cache_blocks (bool) = false,
  17: parquet_file_size (i64) = 0,
  18: explain_level (i32) = 1,
  19: sync_ddl (bool) = false,
  24: disable_outermost_topn (bool) = false,
  26: query_timeout_s (i32) = 0,
  28: appx_count_distinct (bool) = false,
  29: disable_unsafe_spills (bool) = false,
  31: exec_single_node_rows_threshold (i32) = 100,
  32: optimize_partition_key_scans (bool) = false,
  33: replica_preference (i32) = 0,
  34: schedule_random_replica (bool) = false,
  36: disable_streaming_preaggregations (bool) = false,
  37: runtime_filter_mode (i32) = 2,
  38: runtime_bloom_filter_size (i32) = 1048576,
  39: runtime_filter_wait_time_ms (i32) = 0,
  40: disable_row_runtime_filtering (bool) = false,
  41: max_num_runtime_filters (i32) = 10,
  42: parquet_annotate_strings_utf8 (bool) = false,
  43: parquet_fallback_schema_resolution (i32) = 0,
  45: s3_skip_insert_staging (bool) = true,
  46: runtime_filter_min_size (i32) = 1048576,
  47: runtime_filter_max_size (i32) = 16777216,
  48: prefetch_mode (i32) = 1,
  49: strict_mode (bool) = false,
  50: scratch_limit (i64) = -1,
  51: enable_expr_rewrites (bool) = true,
  52: decimal_v2 (bool) = true,
  53: parquet_dictionary_filtering (bool) = true,
  54: parquet_array_resolution (i32) = 0,
  55: parquet_read_statistics (bool) = true,
  56: default_join_distribution_mode (i32) = 0,
  57: disable_codegen_rows_threshold (i32) = 50000,
  58: default_spillable_buffer_size (i64) = 2097152,
  59: min_spillable_buffer_size (i64) = 65536,
  60: max_row_size (i64) = 524288,
  61: idle_session_timeout (i32) = 0,
  62: compute_stats_min_sample_size (i64) = 1073741824,
  63: exec_time_limit_s (i32) = 0,
  64: shuffle_distinct_exprs (bool) = true,
  65: max_mem_estimate_for_admission (i64) = 0,
  66: thread_reservation_limit (i32) = 3000,
  67: thread_reservation_aggregate_limit (i32) = 0,
  68: kudu_read_mode (i32) = 0,
  69: allow_erasure_coded_files (bool) = false,
  70: timezone (string) = "",
  71: scan_bytes_limit (i64) = 0,
  72: cpu_limit_s (i64) = 0,
  73: topn_bytes_limit (i64) = 536870912,
  75: resource_trace_ratio (double) = 0,
  76: num_remote_executor_candidates (i32) = 3,
  77: num_rows_produced_limit (i64) = 0,
}
I0211 08:57:47.067616  3533 impala-server.cc:1006] Found local timezone "SystemV/PST8PDT".
I0211 08:57:47.068898  3533 impala-server.cc:1063] 1c493c0f41a665ad:a2bbe8fa00000000] Registered query query_id=1c493c0f41a665ad:a2bbe8fa00000000 session_id=bb4a41cb1ac98729:91acb8dec2020f99
I0211 08:57:47.068987  3533 Frontend.java:1242] 1c493c0f41a665ad:a2bbe8fa00000000] Analyzing query: SHOW TABLES IN go_impala_repro
I0211 08:57:47.069133  3533 Frontend.java:1282] 1c493c0f41a665ad:a2bbe8fa00000000] Analysis finished.
I0211 08:57:47.069336  3533 impala-server.cc:968] 1c493c0f41a665ad:a2bbe8fa00000000] Execution request: TExecRequest {
  01: stmt_type (i32) = 1,
  02: query_options (struct) = TQueryOptions {
    01: abort_on_error (bool) = false,
    02: max_errors (i32) = 100,
    03: disable_codegen (bool) = false,
    04: batch_size (i32) = 0,
    05: num_nodes (i32) = 0,
    06: max_scan_range_length (i64) = 0,
    07: num_scanner_threads (i32) = 0,
    11: debug_action (string) = "",
    12: mem_limit (i64) = 0,
    15: hbase_caching (i32) = 0,
    16: hbase_cache_blocks (bool) = false,
    17: parquet_file_size (i64) = 0,
    18: explain_level (i32) = 1,
    19: sync_ddl (bool) = false,
    24: disable_outermost_topn (bool) = false,
    26: query_timeout_s (i32) = 0,
    28: appx_count_distinct (bool) = false,
    29: disable_unsafe_spills (bool) = false,
    31: exec_single_node_rows_threshold (i32) = 100,
    32: optimize_partition_key_scans (bool) = false,
    33: replica_preference (i32) = 0,
    34: schedule_random_replica (bool) = false,
    36: disable_streaming_preaggregations (bool) = false,
    37: runtime_filter_mode (i32) = 2,
    38: runtime_bloom_filter_size (i32) = 1048576,
    39: runtime_filter_wait_time_ms (i32) = 0,
    40: disable_row_runtime_filtering (bool) = false,
    41: max_num_runtime_filters (i32) = 10,
    42: parquet_annotate_strings_utf8 (bool) = false,
    43: parquet_fallback_schema_resolution (i32) = 0,
    44: mt_dop (i32) = 0,
    45: s3_skip_insert_staging (bool) = true,
    46: runtime_filter_min_size (i32) = 1048576,
    47: runtime_filter_max_size (i32) = 16777216,
    48: prefetch_mode (i32) = 1,
    49: strict_mode (bool) = false,
    50: scratch_limit (i64) = -1,
    51: enable_expr_rewrites (bool) = true,
    52: decimal_v2 (bool) = true,
    53: parquet_dictionary_filtering (bool) = true,
    54: parquet_array_resolution (i32) = 0,
    55: parquet_read_statistics (bool) = true,
    56: default_join_distribution_mode (i32) = 0,
    57: disable_codegen_rows_threshold (i32) = 50000,
    58: default_spillable_buffer_size (i64) = 2097152,
    59: min_spillable_buffer_size (i64) = 65536,
    60: max_row_size (i64) = 524288,
    61: idle_session_timeout (i32) = 0,
    62: compute_stats_min_sample_size (i64) = 1073741824,
    63: exec_time_limit_s (i32) = 0,
    64: shuffle_distinct_exprs (bool) = true,
    65: max_mem_estimate_for_admission (i64) = 0,
    66: thread_reservation_limit (i32) = 3000,
    67: thread_reservation_aggregate_limit (i32) = 0,
    68: kudu_read_mode (i32) = 0,
    69: allow_erasure_coded_files (bool) = false,
    70: timezone (string) = "",
    71: scan_bytes_limit (i64) = 0,
    72: cpu_limit_s (i64) = 0,
    73: topn_bytes_limit (i64) = 536870912,
    75: resource_trace_ratio (double) = 0,
    76: num_remote_executor_candidates (i32) = 3,
    77: num_rows_produced_limit (i64) = 0,
  },
  04: catalog_op_request (struct) = TCatalogOpRequest {
    01: op_type (i32) = 0,
    02: sync_ddl (bool) = false,
    07: show_tables_params (struct) = TShowTablesParams {
      01: db (string) = "go_impala_repro",
    },
  },
  05: result_set_metadata (struct) = TResultSetMetadata {
    01: columns (list) = list<struct>[1] {
      [0] = TColumn {
        01: columnName (string) = "name",
        02: columnType (struct) = TColumnType {
          01: types (list) = list<struct>[1] {
            [0] = TTypeNode {
              01: type (i32) = 0,
              02: scalar_type (struct) = TScalarType {
                01: type (i32) = 12,
              },
            },
          },
        },
      },
    },
  },
  08: access_events (set) = set<struct>[1] {
    TAccessEvent {
      01: name (string) = "go_impala_repro",
      02: object_type (i32) = 2,
      03: privilege (string) = "ANY",
    },
  },
  09: analysis_warnings (list) = list<string>[0] {
  },
  11: timeline (struct) = TEventSequence {
    01: name (string) = "Query Compilation",
    02: timestamps (list) = list<i64>[3] {
      [0] = 94278,
      [1] = 175204,
      [2] = 189547,
    },
    03: labels (list) = list<string>[3] {
      [0] = "Metadata of all 0 tables cached",
      [1] = "Analysis finished",
      [2] = "Planning finished",
    },
  },
  12: user_has_profile_access (bool) = true,
  14: profile (struct) = TRuntimeProfileNode {
    01: name (string) = "Frontend",
    02: num_children (i32) = 0,
    03: counters (list) = list<struct>[0] {
    },
    04: metadata (i64) = -1,
    05: indent (bool) = false,
    06: info_strings (map) = map<string,string>[0] {
    },
    07: info_strings_display_order (list) = list<string>[0] {
    },
    08: child_counters_map (map) = map<string,set>[1] {
      "" -> set<string>[0] {
      },
    },
  },
}
I0211 08:57:47.072108  3192 rpc-trace.cc:199] RPC call: StatestoreSubscriber.UpdateState(from ::ffff:127.0.0.1:51436)
I0211 08:57:47.072144  3192 admission-controller.cc:758] Full impala-request-queue stats update
I0211 08:57:47.072180  3192 rpc-trace.cc:209] RPC call: statestore-subscriber:StatestoreSubscriber.UpdateState from ::ffff:127.0.0.1:51436 took 0.000ns
I0211 08:57:47.072614  3533 thread.cc:327] Started thread 3564 - query-exec-state:wait-thread
I0211 08:57:47.072659  3533 rpc-trace.cc:209] RPC call: beeswax:BeeswaxService.query from ::ffff:127.0.0.1:39542 took 5.000ms
I0211 08:57:47.072710  3533 rpc-trace.cc:199] RPC call: BeeswaxService.get_state(from ::ffff:127.0.0.1:39542)
I0211 08:57:47.072749  3533 impala-beeswax-server.cc:251] get_state(): query_id=1c493c0f41a665ad:a2bbe8fa00000000
I0211 08:57:47.072779  3533 rpc-trace.cc:209] RPC call: beeswax:BeeswaxService.get_state from ::ffff:127.0.0.1:39542 took 0.000ns
I0211 08:57:47.072819  3533 rpc-trace.cc:199] RPC call: BeeswaxService.fetch(from ::ffff:127.0.0.1:39542)
I0211 08:57:47.072826  3533 impala-beeswax-server.cc:176] fetch(): query_id=1c493c0f41a665ad:a2bbe8fa00000000 fetch_size=1000000
I0211 08:57:47.073945  3533 impala-beeswax-server.cc:179] fetch result: #results=2000 has_more=false
I0211 08:57:47.074069  3533 rpc-trace.cc:209] RPC call: beeswax:BeeswaxService.fetch from ::ffff:127.0.0.1:39542 took 1.000ms
I0211 08:57:47.074839  3533 rpc-trace.cc:199] RPC call: BeeswaxService.get_results_metadata(from ::ffff:127.0.0.1:39542)
I0211 08:57:47.074851  3533 impala-beeswax-server.cc:197] get_results_metadata(): query_id=1c493c0f41a665ad:a2bbe8fa00000000
I0211 08:57:47.074877  3533 rpc-trace.cc:209] RPC call: beeswax:BeeswaxService.get_results_metadata from ::ffff:127.0.0.1:39542 took 0.000ns
`

**Comment by vishjosh** [comment]
@paribhasha : Can you please try Tim's script with the server we have where we have LDAP and SSL enabled . That is the closest we can come to trying to reproduce the problem outside of the enterprise's cluster.

@timarmstrong  we do not have access to the server on which we are seeing the error. We will try to reproduce it in a local set up as best as we can.

**Comment by vishjosh** [comment]
@paribhasha  Can you please create a pull request for the changes we have done so far (also can replace the sample client program with the one you have) . Vsevolod can incorporate the changes in his fix.

**Comment by paribhasha** [comment]
@vishjosh @timarmstrong 

I was able to repro the issue with a DB with 2000 tables (created using https://github.com/timarmstrong/go-impala-repro) in a Server of version: impalad version 2.10.0-cdh5.13.0 RELEASE (build 2511805f1eaa991df1460276c7e9f19d819cd4e4). This is the quickstart.cloudera VM. 

Earlier the issue was seen in Server version: impalad version 2.8.0-cdh5.11.2 RELEASE (build f89269c4b96da14a841e94bdf6d4d48821b0d658)

I bumped up the logging by setting GLOG_v=3 and have collected the impalad INFO logs.
[go-impala-repro-impalad.INFO.log](https://github.com/bippio/go-impala/files/2854426/go-impala-repro-impalad.INFO.log)

Client output:

_go_impala_repro is the database with 2000 tables._

$ go run impala.go
2019/02/12 06:35:41 List of Databases
[_impala_builtins bipp default go_impala_repro nyc_yellow_taxi]
2019/02/12 06:35:41 List of Tables in Database _impala_builtins: []
2019/02/12 06:35:41 List of Tables in Database bipp: [store_info uscrimes]
2019/02/12 06:35:42 List of Tables in Database default: []
2019/02/12 06:35:42 GetResultsMetadata failed: get_results_metadata: wrong method name
2019/02/12 06:35:42 List of Tables in Database go_impala_repro: []
2019/02/12 06:35:42 error in querying database nyc_yellow_taxi: query: wrong method name

**Comment by timarmstrong** [comment]
Hrm, it's strange that it looks like the calling pattern is the same for the earlier databases and go_impala_repro. This is a wild guess, but it could somehow be related to https://issues.apache.org/jira/browse/IMPALA-7101, where get_results_metadata() on beeswax throws an exception that it doesn't declare.

**Comment by timarmstrong** [comment]
I tried running against the latest CDH5 without security and couldn't reproduce.

With the quickstart VM, were you running with security enabled? I'm interested if this is only reproducible with security or if it's somehow related to the version of Impala that's running.

It looks like the error is bubbling up from the go thrift client - https://github.com/apache/thrift/blob/af7ecd6a2b15efe5c6b742cf4a9ccb31bcc1f362/lib/go/thrift/client.go#L46. I'm wondering if somehow the client-server communication is getting out of whack at the thrift layer. It's hard to explain why subsequent queries fail otherwise.

**Comment by vishjosh** [comment]
@timarmstrong  It is most likely with ldap and ssl enabled.  
@paribhasha   can confirm once he is online (in about 7 hours )

**Comment by paribhasha** [comment]
yes, my tests have confirmed now that the problem arises only with security enabled. After disabling SSL and LDAP authentication, I could pass any arbitrary 32 bit integer as fetch_size to the thrift client and not hit the issue.

**Comment by intamyuto** [comment]
This is a transport issue. TSaslTransport (custom wrapper around thrift transport) reads big frames incorrectly. I am working on the patch.
